version: 2.1
jobs:
  build:
    docker:
      -
        image: mh35jp/builddoc:v-0.1.2
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_TOKEN
    steps:
      - checkout
      -
        run:
          command: git submodule update --init
          name: Initializing/updating submodules
      -
        run:
          command: npm install
          name: Installing npm modules
      -
        run:
          command: gulp
          name: Building document
      -
        store_artifacts:
          path: dst/output.pdf
